import sqlite3
import csv
import os

"""
Generated by ChatGPT GPT-5.2
"""

GTFS_DIR = "gtfs/dump"
DB_FILE = "gtfs.sqlite"

conn = sqlite3.connect(DB_FILE)
cur = conn.cursor()

def load_table(filename, table_name):
    path = os.path.join(GTFS_DIR, filename)
    with open(path, newline='', encoding='utf-8') as f:
        reader = csv.reader(f)
        headers = next(reader)

        cur.execute(f'''
            CREATE TABLE IF NOT EXISTS {table_name} (
                {", ".join(h + " TEXT" for h in headers)}
            )
        ''')

        cur.executemany(
            f'INSERT INTO {table_name} VALUES ({",".join("?" for _ in headers)})',
            reader
        )

for file in ["stops.txt", "stop_times.txt", "trips.txt", "routes.txt"]:
    load_table(file, file.replace(".txt", ""))

conn.commit()
